---
title: "Simulation"
author: Yuqi Wang
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Let's simulate something

I have the function

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```


I can simulate by running this line
```{r}
sim_mean_sd(30)
```


## Let's simulate a lot

Let's start with a for loop
```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  output[[i]] = sim_mean_sd(30)
}

bind_rows(output)
```

Let's use a loop function:
```{r}
sim_result = rerun(100, sim_mean_sd(30)) %>% 
  bind_rows()
```

Let's look at results:
```{r}
sim_result %>% 
  ggplot(aes(x = mu_hat)) + geom_density()

sim_result %>% summarize(
  avg_samp_mean = mean(mu_hat),
  sd_samp_mean = sd(mu_hat)
)

sim_result %>% 
  ggplot(aes(x = sigma_hat)) + geom_density()
```


## let's try other sample sizes

```{r}
n_list = 
  list(
    "n_30"  = 30, 
    "n_60"  = 60, 
    "n_120" = 120, 
    "n_240" = 240)

output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(100, sim_mean_sd(n_list[[i]])) %>% 
  bind_rows()
}
```


```{r}
#'cache ='  means run the code for one time and use the saved result everytime you knit. But very easy to break.
sim_result = tibble(
  sample_size = c(30, 60, 120, 240),
  ) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~rerun(100, sim_mean_sd(.x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)
```


Do some data frame things
```{r}
sim_result %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat)) +
  geom_violin()
```


```{r}
sim_result %>% 
  group_by(sample_size) %>% 
  summarize(
    avg_samp_mean = mean(mu_hat),
    sd_samp_mean = sd(mu_hat)
  )
```

